name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.76.0-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Rust environment
        run: |
          cd coverage_test  # Move into the Rust project directory
          rustup update stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
